window.PSR_DATA = {
  copyBlocks: {
    heroKicker: "Pratik",
    heroTitle: "Resume, timeline, agents.",
    heroBody: "BBA, MBA, work, code, and a suite rail.",
    thesis: "Resume, suite, and timeline on one public surface.",
    educationIntro: "BBA and MBA.",
    agenticSuiteIntro:
      "Agent Ops, Switchboard, Palimpsest, and adapters are the suite layer.",
    privacyIntro:
      "The public site shows selected metadata only. Raw marks, IDs, scans, offer letters, finance rows, meeting media, and private notes stay out.",
  },
  lifeTracks: [
    {
      id: "education",
      title: "Education",
      label: "School, BBA, MBA",
      status: "confirmed metadata",
      confirmationStatus: "confirmed",
      summary:
        "Education milestones from school in Bangalore through PES University and an MBA, with private marks and documents excluded.",
    },
    {
      id: "football",
      title: "Football",
      label: "Playing and coaching",
      status: "confirmed metadata",
      confirmationStatus: "confirmed",
      summary:
        "Football appears as coaching proof, field-session work, and the discipline of tracking progress session by session.",
    },
    {
      id: "clothing",
      title: "080 / Clothing",
      label: "Kit culture and making",
      status: "needs image review",
      confirmationStatus: "needs_ceo_confirmation",
      summary:
        "080 connects t-shirts, sewing, embroidery, football kit culture, and visual experiments into a physical-making lane.",
    },
    {
      id: "farming",
      title: "Farming",
      label: "Mushrooms and saffron",
      status: "needs source review",
      confirmationStatus: "needs_ceo_confirmation",
      summary:
        "Mushroom and saffron notes are part of the life archive, but public copy waits for selected images and approved wording.",
    },
    {
      id: "systems",
      title: "Systems",
      label: "Hardware, data, AI",
      status: "high-level only",
      confirmationStatus: "confirmed",
      summary:
        "The systems lane covers hardware, local-first AI, automation, dashboards, and evidence tools without exposing private payloads.",
    },
  ],
  timeline: [
    {
      id: "grade-10",
      date: "2014",
      lane: "education",
      title: "Grade 10",
      publicSummary: "Secondary school milestone in Bangalore, shown without marks, IDs, or raw documents.",
      confidence: "year-level",
      confirmationStatus: "confirmed",
    },
    {
      id: "grade-12",
      date: "2016",
      lane: "education",
      title: "Grade 12 / Pre-University",
      publicSummary: "Pre-university education milestone, kept to public wording only.",
      confidence: "year-level",
      confirmationStatus: "confirmed",
    },
    {
      id: "bba",
      date: "2017-2020",
      lane: "education",
      title: "Bachelor of Business Administration",
      publicSummary: "Business education period at PES University.",
      confidence: "year-level",
      confirmationStatus: "confirmed",
    },
    {
      id: "mba",
      date: "2020-2021",
      lane: "education",
      title: "Master of Business Administration",
      publicSummary: "MBA period recorded in the credential evidence layer.",
      confidence: "year-level",
      confirmationStatus: "confirmed",
    },
    {
      id: "aiff-d",
      date: "2021",
      lane: "football",
      title: "AIFF D coaching certificate",
      publicSummary: "Football coaching proof exists; certificate numbers and scans stay private.",
      confidence: "year-level",
      confirmationStatus: "confirmed",
    },
    {
      id: "080-making",
      date: "2022",
      lane: "clothing",
      title: "080, sewing, and kit culture",
      publicSummary: "A making lane connecting football, clothing, t-shirts, sewing, and embroidery.",
      confidence: "inferred",
      confirmationStatus: "needs_ceo_confirmation",
    },
    {
      id: "farming-track",
      date: "2022",
      lane: "farming",
      title: "Mushrooms and saffron notes",
      publicSummary: "Farming experiments are tracked, with public details waiting for selected media and approved wording.",
      confidence: "inferred",
      confirmationStatus: "needs_ceo_confirmation",
    },
    {
      id: "current-suite",
      date: "2026",
      lane: "systems",
      title: "Evidence and agentic suite",
      publicSummary: "Agent Ops, Switchboard, Palimpsest, and adapters become the layer for working with agent teams.",
      confidence: "current workspace evidence",
      confirmationStatus: "confirmed",
    },
  ],
  education: [
    {
      id: "grade-10",
      title: "Grade 10 CBSE",
      institution: "Delhi Public School Bangalore-North",
      year: "2014",
      publicSummary: "Secondary school credential metadata.",
      confirmationStatus: "confirmed",
      privacyBoundary: "Marks, register numbers, and raw certificate details stay private.",
    },
    {
      id: "grade-12",
      title: "Grade 12 / Pre-University",
      institution: "The Amaatra Academy PU College",
      year: "2016",
      publicSummary: "Pre-university credential metadata.",
      confirmationStatus: "confirmed",
      privacyBoundary: "Subject marks and raw certificate details stay private.",
    },
    {
      id: "bba",
      title: "Bachelor of Business Administration",
      institution: "PES University",
      year: "2020",
      publicSummary: "Business degree metadata.",
      confirmationStatus: "confirmed",
      privacyBoundary: "Transcripts, marks, and raw scans stay private.",
    },
    {
      id: "mba",
      title: "Master of Business Administration",
      institution: "Indiana University of Pennsylvania",
      year: "2021",
      publicSummary: "MBA degree metadata.",
      confirmationStatus: "confirmed",
      privacyBoundary: "Raw certificate scans and identifiers stay private.",
    },
  ],
  proofItems: [
    {
      id: "aiff-d",
      title: "AIFF D Coaching Certificate",
      issuer: "All India Football Federation",
      year: "2021",
      track: "football",
      publicSummary: "Football coaching proof is represented as redacted metadata only.",
      confirmationStatus: "confirmed",
      redactionNote: "Certificate number and raw scan stay private.",
    },
    {
      id: "education-proof",
      title: "Education Proof Wall",
      issuer: "School and university records",
      year: "2014-2021",
      track: "education",
      publicSummary: "Credential names and issuers can be shown without marks, IDs, transcripts, or scans.",
      confirmationStatus: "confirmed",
      redactionNote: "Raw private records stay out.",
    },
  ],
  resumeHighlights: [
    {
      id: "bba-pes",
      title: "BBA",
      detail: "PES University",
      year: "2020",
      kind: "education",
    },
    {
      id: "mba-iup",
      title: "MBA",
      detail: "Indiana University of Pennsylvania",
      year: "2021",
      kind: "education",
    },
    {
      id: "aiff-d",
      title: "AIFF D",
      detail: "Football coaching credential",
      year: "2021",
      kind: "football",
    },
    {
      id: "ai-chatbots",
      title: "AI chatbots",
      detail: "Gemini, OpenAI, RAG, LLM query, and chat API experiments",
      year: "2024-2026",
      kind: "ai",
    },
    {
      id: "eox-vantage",
      title: "EOX Vantage",
      detail: "Work milestone",
      year: "2023",
      kind: "work",
    },
    {
      id: "ayotta",
      title: "Ayotta",
      detail: "Current role",
      year: "2024-current",
      kind: "work",
    },
    {
      id: "agentic-suite",
      title: "Agentic suite",
      detail: "Agent Ops, Switchboard, Palimpsest, public adapter gate",
      year: "2026",
      kind: "systems",
    },
  ],
  aiWork: [
    {
      id: "geminichat",
      title: "Gemini Chat",
      summary: "Streamlit chatbot powered by Gemini Pro and Gemini Pro Vision.",
      href: "https://github.com/Pratikreddy/geminichat",
    },
    {
      id: "llmquerybot",
      title: "LLM Query Bot",
      summary: "Public LLM query bot experiment from the AI tooling archive.",
      href: "https://github.com/Pratikreddy/llmquerybot",
    },
    {
      id: "ai-chat",
      title: "AI Chat API",
      summary: "Session-aware AI chat and RAG backend family represented as public metadata.",
      href: "https://github.com/Pratikreddy/ai-chat",
    },
    {
      id: "openai-api",
      title: "OpenAI API Tests",
      summary: "Public experiments and scripts for OpenAI API usage.",
      href: "https://github.com/Pratikreddy/openai-api",
    },
  ],
  mediaCandidates: [
    {
      id: "football-coaching",
      title: "Football coaching media",
      track: "football",
      publicStatus: "available_after_review",
      rightsStatus: "needs rights review",
      facePrivacyStatus: "needs participant privacy review",
    },
    {
      id: "080-clothing",
      title: "080 and clothing media",
      track: "clothing",
      publicStatus: "available_after_review",
      rightsStatus: "needs rights review",
      facePrivacyStatus: "review before public use",
    },
  ],
  projects: [
    {
      id: "switchboard",
      title: "Switchboard Dashboard",
      date: "2026",
      stack: "Python, FastAPI, local inventory, workflow ledger",
      sourceStatus: "public-safe seed",
      exposure: "public_candidate",
      summary:
        "Control-center and node-workflow dashboard for local projects, snapshots, tasks, and source-state evidence.",
      href: "https://github.com/Pratikreddy/switchboard"
    },
    {
      id: "yt-downloader",
      title: "YouTube Downloader",
      date: "2024-2026",
      stack: "Python, automation, media tooling",
      sourceStatus: "public-safe seed",
      exposure: "public_candidate",
      summary: "Media automation project represented with public repository evidence only.",
      href: "https://github.com/Pratikreddy/yt-downloader"
    }
  ]
};
